Repository swastikbaithalu/DSA_Problems-, pull requests merged in 2022-10, with the labels that each got.

#12 Update readme.md
  README.md
Labels: documentation, hactoberfest, hactoberfest-accepted

#18 Create 2D Array - DS.py
  HackerRank/2D Array - DS.py
Labels: hactoberfest, hactoberfest-accepted

#10 Update the readme.md file
  README.md
Labels: documentation, hactoberfest, hactoberfest-accepted

#23 Update the read me
  README.md
Labels: hactoberfest, hactoberfest-accepted

#24 Update the read me
  README.md
Labels: good first issue, hactoberfest, hactoberfest-accepted

#25 Update the read me
  README.md
Labels: hactoberfest, hactoberfest-accepted

#26 Update the read me now
  README.md
Labels: hactoberfest2021, hactoberfest, hactoberfest-accepted
